//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDS.MDSAppWebServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="ScadaWeb", ConfigurationName="MDSAppWebServiceRef.MDSAppServiceSoap")]
    public interface MDSAppServiceSoap {
        
        // CODEGEN: 命名空间 ScadaWeb 的元素名称 bytesOfMessage 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="ScadaWeb/ReceiveMDSMessage", ReplyAction="*")]
        MDS.MDSAppWebServiceRef.ReceiveMDSMessageResponse ReceiveMDSMessage(MDS.MDSAppWebServiceRef.ReceiveMDSMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ScadaWeb/ReceiveMDSMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<MDS.MDSAppWebServiceRef.ReceiveMDSMessageResponse> ReceiveMDSMessageAsync(MDS.MDSAppWebServiceRef.ReceiveMDSMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMDSMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMDSMessage", Namespace="ScadaWeb", Order=0)]
        public MDS.MDSAppWebServiceRef.ReceiveMDSMessageRequestBody Body;
        
        public ReceiveMDSMessageRequest() {
        }
        
        public ReceiveMDSMessageRequest(MDS.MDSAppWebServiceRef.ReceiveMDSMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ScadaWeb")]
    public partial class ReceiveMDSMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] bytesOfMessage;
        
        public ReceiveMDSMessageRequestBody() {
        }
        
        public ReceiveMDSMessageRequestBody(byte[] bytesOfMessage) {
            this.bytesOfMessage = bytesOfMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMDSMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMDSMessageResponse", Namespace="ScadaWeb", Order=0)]
        public MDS.MDSAppWebServiceRef.ReceiveMDSMessageResponseBody Body;
        
        public ReceiveMDSMessageResponse() {
        }
        
        public ReceiveMDSMessageResponse(MDS.MDSAppWebServiceRef.ReceiveMDSMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="ScadaWeb")]
    public partial class ReceiveMDSMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] ReceiveMDSMessageResult;
        
        public ReceiveMDSMessageResponseBody() {
        }
        
        public ReceiveMDSMessageResponseBody(byte[] ReceiveMDSMessageResult) {
            this.ReceiveMDSMessageResult = ReceiveMDSMessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MDSAppServiceSoapChannel : MDS.MDSAppWebServiceRef.MDSAppServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MDSAppServiceSoapClient : System.ServiceModel.ClientBase<MDS.MDSAppWebServiceRef.MDSAppServiceSoap>, MDS.MDSAppWebServiceRef.MDSAppServiceSoap {
        
        public string Url="";
        public MDSAppServiceSoapClient() {
        }
        
        public MDSAppServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MDSAppServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MDSAppServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MDSAppServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MDS.MDSAppWebServiceRef.ReceiveMDSMessageResponse MDS.MDSAppWebServiceRef.MDSAppServiceSoap.ReceiveMDSMessage(MDS.MDSAppWebServiceRef.ReceiveMDSMessageRequest request) {
            return base.Channel.ReceiveMDSMessage(request);
        }
        
        public byte[] ReceiveMDSMessage(byte[] bytesOfMessage) {
            MDS.MDSAppWebServiceRef.ReceiveMDSMessageRequest inValue = new MDS.MDSAppWebServiceRef.ReceiveMDSMessageRequest();
            inValue.Body = new MDS.MDSAppWebServiceRef.ReceiveMDSMessageRequestBody();
            inValue.Body.bytesOfMessage = bytesOfMessage;
            MDS.MDSAppWebServiceRef.ReceiveMDSMessageResponse retVal = ((MDS.MDSAppWebServiceRef.MDSAppServiceSoap)(this)).ReceiveMDSMessage(inValue);
            return retVal.Body.ReceiveMDSMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MDS.MDSAppWebServiceRef.ReceiveMDSMessageResponse> MDS.MDSAppWebServiceRef.MDSAppServiceSoap.ReceiveMDSMessageAsync(MDS.MDSAppWebServiceRef.ReceiveMDSMessageRequest request) {
            return base.Channel.ReceiveMDSMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<MDS.MDSAppWebServiceRef.ReceiveMDSMessageResponse> ReceiveMDSMessageAsync(byte[] bytesOfMessage) {
            MDS.MDSAppWebServiceRef.ReceiveMDSMessageRequest inValue = new MDS.MDSAppWebServiceRef.ReceiveMDSMessageRequest();
            inValue.Body = new MDS.MDSAppWebServiceRef.ReceiveMDSMessageRequestBody();
            inValue.Body.bytesOfMessage = bytesOfMessage;
            return ((MDS.MDSAppWebServiceRef.MDSAppServiceSoap)(this)).ReceiveMDSMessageAsync(inValue);
        }
    }
}
